name: ellie_core
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  flutter:
    sdk: flutter
  honeywell_scanner: ^4.0.0+14
  intl: ^0.17.0
  just_audio: ^0.9.25
  liquidity_gallery:
    git:
      url: https://github.com/LiquidityGallery/liquidity_gallery.git
      ref: main
  package_info_plus: ^1.4.2
  pdf: ^3.8.1
  printing: ^5.9.1
  audio_session: ^0.1.10
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter: null
